{"name": "test_01_login_error[data2]", "status": "passed", "attachments": [{"name": "log", "source": "05825036-5737-413a-b2a8-473f28624569-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'Caseid': 3, 'module': '登录', 'title': '输入不符规则的用户名', 'username': '123654', 'password': '222', 'expect': '请输入正确的手机号'}"}], "start": 1592286160099, "stop": 1592286165892, "uuid": "b43e145f-07d3-49b6-8544-920805f75669", "historyId": "823adf4c3db60aa5e397d42c2f4291a7", "fullName": "Cases.test_login#test_01_login_error[data2]", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Danny"}, {"name": "thread", "value": "14124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test_login"}]}